routes/admin.php
<?php

use App\Http\Controllers\Admin\AbilityController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::resource('user', UserController::class, [
    'only' => ['index', 'edit', 'update', 'destroy']
]);

Route::resource('ability', AbilityController::class, [
    'only' => ['index', 'edit', 'update']
]);

Route::resource('role', RoleController::class, [
    'only' => ['index', 'edit', 'update']
]);

routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MessageController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); })
    ->middleware('guest')
    ->name('home');

Auth::routes(['verify' => true]);

Route::get('/dashboard', [HomeController::class, 'index'])
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::resource('message', MessageController::class, [
    'except' => ['show'],
])->middleware(['auth', 'verified']);

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Message extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'content',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Message\StoreRequest;
use App\Http\Requests\Message\UpdateRequest;
use App\Models\Message;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

class MessageController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Message::class, 'message');
    }

    public function index()
    {
        $messages = Auth::user()->messages
            ? Auth::user()->messages()->orderByDesc('created_at')->paginate(10)
            : collect();

        return view('message.index', [
            'messages' => $messages,
        ]);
    }

    public function create()
    {
        return view('message.create');
    }

    public function store(StoreRequest $request): RedirectResponse
    {
        Auth::user()->messages()->create($request->validated());

        return redirect()->route('dashboard')->with([
            'success' => "Pomyślnie utworzono wiadomość"
        ]);
    }

    public function edit(Message $message)
    {
        return view('message.edit', [
            'message' => $message,
        ]);
    }

    public function update(UpdateRequest $request, Message $message): RedirectResponse
    {
        $message->update($request->validated());

        return redirect()->route('dashboard')->with([
            'success' => "Pomyślnie zaktualizowano wiadomość"
        ]);
    }

    public function destroy(Message $message): RedirectResponse
    {
        $message->delete();

        return redirect()->route('message.index')->with([
            'success' => "Pomyślnie usunięto wiadomość"
        ]);
    }
}

resources/views/message/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <span class="h2" style="text-shadow: 1px 1px 1px #gray">
                    Nowa wiadomość
                </span>
            </div>
            <div class="card mt-5 shadow">
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form method="post" action="{{ route('message.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="title">Nagłówek</label>
                            <input type="text" class="form-control" name="title" value="{{ old('title') }}">
                        </div>
                        <div class="form-group mt-4">
                            <label for="content">Treść wiadomości</label>
                            <textarea type="text" class="form-control" name="content" rows="10">{{ old('content') }}</textarea>
                        </div>
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary">Zapisz</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/message/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <span class="h2" style="text-shadow: 1px 1px 1px #gray">
                    Edycja wiadomości
                </span>
            </div>
            <div class="card mt-5 shadow">
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form method="post" action="{{ route('message.update', $message) }}">
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <label for="title">Nagłówek</label>
                            <input type="text" class="form-control" name="title" value="{{ $message->title }}">
                        </div>
                        <div class="form-group mt-4">
                            <label for="content">Treść wiadomości</label>
                            <textarea type="text" class="form-control" name="content" rows="10">{{ $message->content }}</textarea>
                        </div>
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary">Zapisz</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/message/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <span class="h2">
                    Moje wiadomoci
                </span>
            </div>
            <div class="col-lg-8">
                @if($messages->isNotEmpty())
                    @foreach($messages as $message)
                        <div class="card mt-5 shadow">
                            <div class="card-header">
                                <strong>{{ $message->title }}</strong>
                                <small class="text-secondary float-end">
                                    {{ \Carbon\Carbon::parse($message->created_at)->format('H:i d.m.Y') }}
                                </small>
                            </div>
                            <div class="card-body">
                                {{ $message->content }}
                            </div>
                            <div class="card-footer text-end">
                                @can('update', $message)
                                <a href="{{ route('message.edit', $message) }}" class="btn btn-primary">
                                    Edytuj
                                </a>
                                @endcan
                                @can('delete', $message)
                                <a class="btn btn-danger" href="{{ route('message.destroy', $message) }}"
                                   onclick="event.preventDefault();
                                   if(confirm('Czy na pewno chcesz usunąć wiadomość?')){
                                       document.getElementById('logout-form-{{ $message->id }}').submit();
                                   }
                                ">
                                    {{ __('Usuń') }}
                                </a>
                                <form id="logout-form-{{ $message->id }}" action="{{ route('message.destroy', $message) }}" method="POST" class="d-none">
                                    @csrf
                                    @method('delete')
                                </form>
                                @endcan
                            </div>
                        </div>
                    @endforeach
                @endif
            </div>
            <div class="col-lg-8 d-flex justify-content-center mt-5">
                {{ $messages->links() }}
            </div>
        </div>
    </div>
@endsection