routes/admin.php
<?php

use App\Http\Controllers\Admin\AbilityController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::resource('user', UserController::class, [
    'only' => ['index', 'edit', 'update', 'destroy']
]);

Route::resource('ability', AbilityController::class, [
    'only' => ['index', 'edit', 'update']
]);

Route::resource('role', RoleController::class, [
    'only' => ['index', 'edit', 'update']
]);

routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MessageController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); })
    ->middleware('guest')
    ->name('home');

Auth::routes(['verify' => true]);

Route::get('/dashboard', [HomeController::class, 'index'])
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::resource('message', MessageController::class, [
    'except' => ['show'],
])->middleware(['auth', 'verified']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'role_id',
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $appends = [
        'policies',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function messages(): HasMany
    {
        return $this->hasMany(Message::class);
    }

    public function role(): BelongsTo
    {
        return $this->belongsTo(Role::class);
    }

    public function abilities(): BelongsToMany
    {
        return $this->belongsToMany(Ability::class, 'user_ability');
    }

    public function getPoliciesAttribute() {
        $roleAbilities = $this->role->abilities()->withPivot(['can'])->get();
        $userAbilities = $this->abilities()->withPivot(['can'])->get();

        return $roleAbilities->merge($userAbilities)->mapWithKeys(function ($ability) {
            return [
                $ability->slug => $ability->pivot->can
            ];
        });
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\User\UpdateRequest;
use App\Models\Ability;
use App\Models\Message;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class UserController extends Controller
{
    const FILTER_ABILITY_VALUE = 2;

    public function __construct()
    {
        $this->authorizeResource(User::class, 'user');
    }

    public function index()
    {
        $users = User::all();

        return view('admin.user.index', [
            'users' => $users,
        ]);
    }

    public function edit(User $user)
    {
        $roles = Role::all();
        $abilities = Ability::all();
        $userAbilities = $user->abilities()
            ->withPivot(['can'])
            ->get()
            ->mapWithKeys(function ($userAbility) {
                return [
                    $userAbility->id => $userAbility->pivot->can,
                ];
            });

        return view('admin.user.edit', [
            'user' => $user,
            'roles' => $roles,
            'abilities' => $abilities,
            'userAbilities' => $userAbilities,
        ]);
    }

    public function update(UpdateRequest $request, User $user): RedirectResponse
    {
        $data = $request->validated();
        $abilities = collect($data['can'])->reject(function ($ability) {
            return $ability == self::FILTER_ABILITY_VALUE;
        })->mapWithKeys(function ($ability, $id) {
            return [
                $id => [
                    'can' => $ability,
                ]
            ];
        });

        $user->update($data);
        $user->abilities()->sync($abilities);

        return redirect()->route('admin.user.index')->with([
            'success' => 'Pomyślnie zaktualizowano użytkownika'
        ]);
    }

    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()->route('admin.user.index')->with([
            'success' => 'Pomyślnie zaktualizowano użytkownika'
        ]);
    }
}

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <span class="h2" style="text-shadow: 1px 1px 1px #gray">
                    Edycja użytkownika
                </span>
            </div>
            <div class="card mt-5 shadow">
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('admin.user.update', $user) }}" method="POST">
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="col-lg-4 offset-lg-4 mt-2">
                                <div class="form-group">
                                    <label for="name">Imię</label>
                                    <input type="text" class="form-control" name="name" value="{{ $user->name }}" required>
                                </div>
                            </div>
                            <div class="col-lg-4 offset-lg-4 mt-2">
                                <div class="form-group">
                                    <label for="role_id">Grupa uprawnień</label>
                                    <select name="role_id" class="form-select" required>
                                        @foreach($roles as $role)
                                            <option value="{{ $role->id }}" @if($role->id === $user->role->id) selected @endif>{{ $role->title }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-4 offset-lg-4 mt-2">
                                <div class="form-group">
                                    <label for="name">Email</label>
                                    <input type="text" class="form-control" name="email" value="{{ $user->email }}" required>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <table class="table mt-5">
                                    <thead>
                                    <tr>
                                        <td colspan="2" class="text-center">
                                            <strong>Uprawnienia</strong>
                                        </td>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($abilities as $ability)
                                        <tr>
                                            <td>{{ $ability->title }}</td>
                                            <td class="text-end">
                                                <input type="radio"
                                                       class="btn-check"
                                                       name="can[{{$ability->id}}]"
                                                       id="success-outlined-{{$ability->id}}"
                                                       autocomplete="off"
                                                       value="1"
                                                       @if(isset($userAbilities[$ability->id]) && $userAbilities[$ability->id] == 1) checked @endif>
                                                <label class="btn btn-outline-success" for="success-outlined-{{$ability->id}}">
                                                    Zezwól
                                                </label>

                                                <input type="radio"
                                                       class="btn-check"
                                                       name="can[{{$ability->id}}]"
                                                       id="primary-outlined-{{$ability->id}}"
                                                       autocomplete="off"
                                                       value="2"
                                                       @if(!isset($userAbilities[$ability->id])) checked @endif>
                                                <label class="btn btn-outline-primary" for="primary-outlined-{{$ability->id}}">
                                                    Dziedzić
                                                </label>

                                                <input type="radio"
                                                       class="btn-check"
                                                       name="can[{{$ability->id}}]"
                                                       id="danger-outlined-{{$ability->id}}"
                                                       autocomplete="off"
                                                       value="0"
                                                       @if(isset($userAbilities[$ability->id]) && $userAbilities[$ability->id] == 0) checked @endif>
                                                <label class="btn btn-outline-danger" for="danger-outlined-{{$ability->id}}">
                                                    Zabroń
                                                </label>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-lg-12 text-center mt-4">
                                <button type="submit" class="btn btn-primary">Zapisz</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <span class="h2" style="text-shadow: 1px 1px 1px #gray">
                    Użytkownicy
                </span>
            </div>
            <div class="card mt-5 shadow">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Imię</th>
                                <th>Grupa uprawnień</th>
                                <th>Email</th>
                                <th>Data założenia konta</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->role->title }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $user->created_at)->format('d.m.Y, H:i') }}</td>
                                    <td class="text-end">
                                        @can('update', $user)
                                        <a href="{{ route('admin.user.edit', $user) }}" class="btn btn-primary">
                                            Edytuj
                                        </a>
                                        @endcan
                                        @can('delete', $user)
                                        <a class="btn btn-danger" href="{{ route('admin.user.destroy', $user) }}"
                                           onclick="event.preventDefault();
                                                   if(confirm('Czy na pewno chcesz usunąć użytkownika?')){
                                                   document.getElementById('logout-form-{{ $user->id }}').submit();
                                                   }
                                                   ">
                                            {{ __('Usuń') }}
                                        </a>

                                        <form id="logout-form-{{ $user->id }}" action="{{ route('admin.user.destroy', $user) }}" method="POST" class="d-none">
                                            @csrf
                                            @method('delete')
                                        </form>
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection